//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailwayCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class SegmentLength
    {
        public int Id { get; set; }
        public int StartWaypointId { get; set; }
        public int EndWaypointId { get; set; }
        public int Length { get; set; }
    
        public virtual Waypoint EndWaypoint { get; set; }
        public virtual Waypoint StartWaypoint { get; set; }
    }
}
