//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailwayCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int Id { get; set; }
        public int PassengerId { get; set; }
        public decimal Price { get; set; }
        public int WagonId { get; set; }
        public int RouteId { get; set; }
        public System.DateTime BuyDate { get; set; }
        public int InStationId { get; set; }
        public int OutStationId { get; set; }
        public int Length { get; set; }
        public Nullable<System.DateTime> InTime { get; set; }
        public Nullable<System.DateTime> OutTime { get; set; }
    
        public virtual Passenger Passenger { get; set; }
        public virtual Route Route { get; set; }
        public virtual Wagon Wagon { get; set; }
        public virtual Station InStation { get; set; }
        public virtual Station OutStation { get; set; }
    }
}
