//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailwayCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class WaypointStation
    {
        public int StationId { get; set; }
        public int WaypointId { get; set; }
        public string StationName { get; set; }
    }
}
