//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailwayCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Waypoint
    {
        public Waypoint()
        {
            this.RoadNets = new HashSet<RoadNet>();
            this.NextRoadNets = new HashSet<RoadNet>();
            this.PrevRoadNets = new HashSet<RoadNet>();
            this.SegmentLengths = new HashSet<SegmentLength>();
            this.SegmentLengths1 = new HashSet<SegmentLength>();
        }
    
        public int Id { get; set; }
        public int StationId { get; set; }
    
        public virtual ICollection<RoadNet> RoadNets { get; set; }
        public virtual ICollection<RoadNet> NextRoadNets { get; set; }
        public virtual ICollection<RoadNet> PrevRoadNets { get; set; }
        public virtual Station Station { get; set; }
        public virtual ICollection<SegmentLength> SegmentLengths { get; set; }
        public virtual ICollection<SegmentLength> SegmentLengths1 { get; set; }
    }
}
