//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailwayCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        public Worker()
        {
            this.Trains = new HashSet<Train>();
            this.Wagons = new HashSet<Wagon>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public int LengthOfService { get; set; }
        public decimal Salary { get; set; }
    
        public virtual ICollection<Train> Trains { get; set; }
        public virtual ICollection<Wagon> Wagons { get; set; }
    }
}
